server:
  port: 8082
  servlet:
    context-path: /magneto

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mutant
    username: mutant
    password: mutantMeli1*
    initialization-mode: always
    schema: classpath:schema.sql

cache:
  time: 1
  defaultTime: 1